fixed Unity 2023 textmesh pro API incompatibility
RageAgainstThePixel/com.fonts.material-icons pull request #4
Opened 2024-12-05 18:07 UTC by Peaj

Changed the `CreateFontAsset` call to use the new Text Mesh Pro API for Unity versions from 2023 and newer.
Used makros to maintain backwards compatibility.
Tested in Unity 2019.4.28f1, 2023.2.20f1 and 6000.0.25f1

Thanks for this useful package!
Would be great if you could merge the pull request and release a new version on NPM so it can still be used beyond Unity 2023.

Fixes #3

2024-12-05 18:23 UTC, StephenHodgson commented
would be nice to see this in https://github.com/RageAgainstThePixel/com.fonts.roboto as well

2024-12-05 18:24 UTC, StephenHodgson requested changes
Looks good.

Just needs to increment the version in package.json to 1.0.1

2024-12-05 18:37 UTC, Peaj commented
Updated the package version to 1.0.1.
Will see about roboto tomorrow. If its the same code it could easily be fixed on github directly I guess.

2024-12-05 18:40 UTC, StephenHodgson approved these changes

2024-12-05 18:41 UTC, merged

2024-12-12 09:59 UTC, Peaj commented
> would be nice to see this in https://github.com/RageAgainstThePixel/com.fonts.roboto as well

Your roboto package does not use the same TMP API calls and works correctly without changes in Unity 6.
So I suppose there is nothing to be fixed there.